// src/app/lib/my-therapist-mock.ts
// Mock data for "دوست روانشناس من" - used as fallback when backend is not yet ready

import type { TherapistProfile, SupportGroup } from "./my-therapist-api";

export const MOCK_THERAPISTS: TherapistProfile[] = [
  {
    id: "t1",
    name: "دکتر مریم احمدی",
    avatarUrl: "/avatars/therapist-1.jpg",
    credentials: ["دکترای روانشناسی بالینی", "عضو سازمان نظام روانشناسی"],
    specialties: ["اضطراب", "افسردگی", "روابط زناشویی"],
    bio: "بیش از ۱۲ سال تجربه در درمان اختلالات اضطرابی و خلقی با رویکرد شناختی-رفتاری (CBT).",
    yearsOfExperience: 12,
    pricePerSession: 450000,
    modes: ["online", "in_person"],
    rating: 4.9,
    reviewsCount: 187,
    city: "تهران",
    verified: true,
    matchScore: 96,
    availableSlots: [
      { date: "۱۸ آبان", time: "۱۶:۰۰" },
      { date: "۱۸ آبان", time: "۱۸:۰۰" },
      { date: "۱۹ آبان", time: "۱۰:۰۰" },
    ],
  },
  {
    id: "t2",
    name: "دکتر سعید رضایی",
    avatarUrl: "/avatars/therapist-2.jpg",
    credentials: ["کارشناس ارشد روانشناسی بالینی", "تربیت‌شده انجمن روانکاوی"],
    specialties: ["خانواده‌درمانی", "اعتیاد", "تروما"],
    bio: "متخصص خانواده‌درمانی و کار با موارد پیچیده تروما.",
    yearsOfExperience: 9,
    pricePerSession: 380000,
    modes: ["online", "in_person"],
    rating: 4.8,
    reviewsCount: 142,
    city: "تهران",
    verified: true,
    matchScore: 91,
    availableSlots: [
      { date: "۱۷ آبان", time: "۱۴:۰۰" },
      { date: "۱۸ آبان", time: "۱۹:۰۰" },
    ],
  },
  {
    id: "t3",
    name: "دکتر زهرا کریمی",
    avatarUrl: "/avatars/therapist-3.jpg",
    credentials: ["دکترای مشاوره", "روان‌درمانگر گروه"],
    specialties: ["تنهایی", "روابط بین‌فردی", "رشد فردی"],
    bio: "تمرکز اصلی من کار با جوانان و افراد در دوره‌های گذار زندگی است.",
    yearsOfExperience: 7,
    pricePerSession: 320000,
    modes: ["online"],
    rating: 4.7,
    reviewsCount: 98,
    city: "اصفهان",
    verified: true,
    matchScore: 88,
    availableSlots: [
      { date: "۱۸ آبان", time: "۲۰:۰۰" },
      { date: "۱۹ آبان", time: "۲۰:۰۰" },
    ],
  },
];

export const MOCK_GROUPS: SupportGroup[] = [
  {
    id: "g1",
    name: "گروه «نفس‌های آرام»",
    topic: "مدیریت اضطراب و استرس",
    description: "گروه ۱۰ نفره برای افرادی که با اضطراب مزمن دست‌وپنجه نرم می‌کنند.",
    facilitatorName: "دکتر مریم احمدی",
    facilitatorId: "t1",
    schedule: "هر سه‌شنبه، ۱۹:۰۰ تا ۲۰:۳۰",
    mode: "online",
    capacity: 10,
    membersCount: 7,
    pricePerMonth: 980000,
    confidentialityLevel: "high",
    rules: ["محرمانگی کامل", "حضور منظم در حداقل ۸۰٪ جلسات"],
    matchScore: 94,
    imageUrl: "/groups/calm.jpg",
  },
  {
    id: "g2",
    name: "گروه «همراه پس از طلاق»",
    topic: "بازسازی پس از جدایی",
    description: "فضایی برای زنان و مردانی که در مسیر بازسازی زندگی پس از جدایی هستند.",
    facilitatorName: "دکتر سعید رضایی",
    facilitatorId: "t2",
    schedule: "هر شنبه، ۲۰:۰۰ تا ۲۱:۳۰",
    mode: "online",
    capacity: 8,
    membersCount: 6,
    pricePerMonth: 1200000,
    confidentialityLevel: "high",
    rules: ["محرمانگی مطلق", "بدون نام بردن از طرف مقابل"],
    matchScore: 89,
    imageUrl: "/groups/divorce.jpg",
  },
];
