version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://raaviiplatform.com
        NEXT_PUBLIC_SITE_URL: https://raaviiplatform.com
        NEXT_PUBLIC_ENV: production
    container_name: raavi-frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
